services:
  backend:
    build: ./backend
    container_name: face-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/faces.db:/app/faces.db
      - ./backend/model:/app/model
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: face-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules   # ✅ quan trọng
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  frontend_node_modules: {}
